### PR TITLE
feat: allow customize antd components with tailwind

### PR DESCRIPTION
**Pull request by LongJohnSilver1504**

### CODE REVIEW

**Comment by hongfaqiu** [comment]
I don't think this configuration should be enabled as the default option for templates, perhaps some people prefer to use inline styles to override the default styles of antd

**Comment by hongfaqiu** [comment]
Antd5 employs the default CSS-in-JS solution, which causes it to transfer large HTML files during SSR rendering, adding a burden to the server. 
There is another [branch ](https://github.com/hongfaqiu/nextjs13-with-antd-tailwindcss/tree/no-css-in-js)in this repository that uses a CSS solution similar to Antd4, but it causes layout changes by loading components before loading styles during the initial page load. 
Antd5 may be more suitable for a CSR environment, and a good development experience can be achieved by using UmiJS. 
There are other powerful component libraries that offer better support for SSR, such as Semi-Design (https://github.com/DouyinFE/semi-design), whose usage is similar to Antd.

**Comment by hongfaqiu** [comment]
Hi, if you are interested in [UmiJS ](https://github.com/umijs/umi) and CSR, I created a template [umijs4-with-antd5-tailwindcss](https://github.com/hongfaqiu/umijs4-with-antd5-tailwindcss), with an online demo too.

**Comment by LongJohnSilver1504** [comment]
Thanks @hongfaqiu  I really appreciate  your time.
If you like we could kept in touch and I could  give you my personal email and we could talk about technologies frameworks  and programming.
Sure Im going to check this new demo
Thanks!!!

**Comment by hongfaqiu** [comment]
I am very willing to continue communicating with you. I have only been exposed to front-end development for a short period of time, and there are many areas in which I can learn from you.
My personal email address is [951142905@qq.com](mailto:951142905@qq.com), same as github email.
This PR will be closed.

**Pull request closed without merging**
